[package]
name = "hurl-parser"
version = "0.0.1-SNAPSHOT"
edition = "2021"
license = "MIT"
description = "A parser for hurl files"
repository = "https://github.com/crwebb85/hurl-language-server"

[dependencies]
chumsky = "=1.0.0-alpha.8"
insta = "1.41.1"
ordered-float = "4.6.0"
