[package]
name = "hurl-language-server"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
env_logger = "0.11.5"
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
tower-lsp = { version = "0.20.0", features = ["proposed"] }
log = "0.4.22"
dashmap = "6.1.0"
ropey = "1.6.1"
hurl-parser = { path = "../hurl-parser" }
pico-args = "0.5.0"

[build-dependencies]
chrono = "0.4.39"
